name: Do2Day-Continuous-Integration

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
